---
swagger: "2.0"
info:
  description: "Rest API for workers to pull jobs and report progress, liveness and\
    \ completion"
  version: "1.0.0"
  title: "FPC Compute Worker API"
  termsOfService: "http://www.autodesk.com"
  contact:
    name: "Forge platform and Components - Compute team"
    url: "http://www.autodesk.com"
    email: "fpc-compute@autodesk.com"
  license:
    name: "Autodesk"
    url: "http://www.autodesk.com"
host: "virtserver.swaggerhub.com"
basePath: "/fpc-compute/worker/1.0.0"
schemes:
- "https"
- "http"
consumes:
- "application/vnd.api+json"
produces:
- "application/vnd.api+json"
paths:
  /jobs/poll:
    post:
      description: "Returns a job specifc to the service type\n"
      operationId: "pollForJob"
      parameters:
      - in: "body"
        name: "pollData"
        description: "name of service to pull the jobs for"
        required: true
        schema:
          $ref: "#/definitions/poll_for_job"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/Job"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /jobs/progress:
    post:
      description: "report job progress"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/Conclusion"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/HeartbeatResponse"
  /jobs/complete:
    post:
      description: "conclude job"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/Conclusion"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/HeartbeatResponse"
  /token:
    get:
      description: "get auth token"
      parameters:
      - name: "scope"
        in: "query"
        description: "scope"
        required: false
        type: "string"
      responses:
        200:
          description: "token"
          schema:
            $ref: "#/definitions/inline_response_200"
  /heartbeat:
    post:
      description: "liveness post"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/Heartbeat"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/HeartbeatResponse"
definitions:
  poll_for_job:
    allOf:
    - $ref: "#/definitions/Service"
    - required:
      - "workerID"
      properties:
        workerID:
          type: "string"
          example: "worker1"
  Conclusion:
    required:
    - "jobID"
    - "result"
    - "workerID"
    properties:
      result:
        type: "string"
        enum:
        - "SUCCEDED"
        - "FAILED"
        - "CANCELED"
      jobID:
        type: "string"
      workerID:
        type: "string"
  HeartbeatResponse:
    properties:
      canceled:
        type: "boolean"
  Heartbeat:
    required:
    - "details"
    - "progress"
    properties:
      progress:
        type: "integer"
      details:
        type: "string"
  Service:
    required:
    - "service_name"
    properties:
      service_name:
        type: "string"
        example: "sample-service:1.0.0"
  Payload:
    type: "object"
    example:
      project_url: "www.autodesk.com"
  Job:
    allOf:
    - $ref: "#/definitions/Service"
    - $ref: "#/definitions/Payload"
    - required:
      - "id"
      properties:
        id:
          type: "string"
          example: "R8TEDg7tRoaUJ_ZfEI8ziDIyTGFVUlFQSXZSdmhlNmdLekhsV3IxZGUyV0hHeUFFVEtsR0ZDd2RnQ2UyTT0"
          description: "Identifier for the job"
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  inline_response_200:
    properties:
      token:
        type: "string"
parameters:
  body_poll_for_job:
    in: "body"
    name: "body"
    description: "describes the job type to fetch job from"
    required: true
    schema:
      $ref: "#/definitions/poll_for_job"
