---
swagger: "2.0"
info:
  description: "Rest API for workers to pull jobs and report progress, liveness and\
    \ completion"
  version: "1.0.0"
  title: "FPC Compute Worker"
  termsOfService: "http://www.autodesk.com"
  contact:
    name: "Swagger API Team"
    url: "http://www.autodesk.com"
    email: "fpc-compute@autodesk.com"
  license:
    name: "Autodesk"
    url: "http://www.autodesk.com"
host: "virtserver.swaggerhub.com"
basePath: "/fpc-compute/worker/1.0.0"
schemes:
- "https"
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /complete:
    post:
      description: "conclude job"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/Conclusion"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/HeartbeatResponse"
  /token:
    get:
      description: "get auth token"
      parameters:
      - name: "scope"
        in: "query"
        description: "scope"
        required: false
        type: "string"
      responses:
        200:
          description: "token"
          schema:
            $ref: "#/definitions/inline_response_200"
  /heartbeat:
    post:
      description: "liveness post"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/Heartbeat"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/HeartbeatResponse"
  /poll:
    post:
      description: "Returns a job specifc to the service type"
      operationId: "pollForJob"
      parameters:
      - in: "body"
        name: "pollData"
        description: "name of service to pull the jobs for"
        required: true
        schema:
          $ref: "#/definitions/PollData"
      responses:
        200:
          description: "response"
          schema:
            $ref: "#/definitions/Job1"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Conclusion:
    required:
    - "jobID"
    - "result"
    - "workerID"
    properties:
      result:
        type: "string"
        enum:
        - "SUCCEDED"
        - "FAILED"
        - "CANCELED"
      jobID:
        type: "string"
      workerID:
        type: "string"
  HeartbeatResponse:
    properties:
      canceled:
        type: "boolean"
  Heartbeat:
    properties:
      jobID:
        type: "string"
      workerID:
        type: "string"
  PollData:
    required:
    - "service"
    - "workerID"
    properties:
      service:
        $ref: "#/definitions/Service"
      workerID:
        type: "string"
        example: "worker1"
  Service:
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "sample-service:1.0.0"
  Job1:
    required:
    - "id"
    - "payload"
    properties:
      id:
        type: "string"
      payload:
        type: "object"
        properties: {}
      service:
        $ref: "#/definitions/Service"
  Job:
    required:
    - "id"
    - "payload"
    properties:
      id:
        type: "string"
        example: "R8TEDg7tRoaUJ_ZfEI8ziDIyTGFVUlFQSXZSdmhlNmdLekhsV3IxZGUyV0hHeUFFVEtsR0ZDd2RnQ2UyTT0"
      payload:
        type: "object"
        properties: {}
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  inline_response_200:
    properties:
      token:
        type: "string"
