swagger: "2.0"
info:
  version: 1.0.0
  title: "FPC Compute Worker"
  description: Rest API for workers to pull jobs and report progress, liveness and completion
  termsOfService: http://www.autodesk.com
  contact:
    name: Swagger API Team
    email: fpc-compute@autodesk.com
    url: http://www.autodesk.com
  license:
    name: Autodesk
    url: http://www.autodesk.com
host: fpccomputeworker.swagger.io
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /token:
    get:
      description: get auth token
      parameters:
        - name: scope
          in: query
          description: scope
          required: false
          type: string
      responses:
        200:
          description: token
          schema:
            properties:
              token:
                type: string
  /heartbeat:
    post:
      description: liveness post
      parameters:
        - name: data
          in: body
          schema:
            $ref: '#/definitions/Heartbeat'
      responses:
        200:
          description: response
          schema:
            $ref: '#/definitions/HeartbeatResponse'
  /acknowledge:
    post:
      description: acknowledge task received
      parameters:
        - name: AckData
          in: body
          description: acknowledge receipt
          required: true
          schema:
            $ref: '#/definitions/AckData'
      responses:
        200:
          description: acknowledged
            
  /poll:
    post:
      description: Returns a job specifc to the service type
      operationId: pollForJob
      parameters:
        - name: pollData
          in: body
          description: name of service to pull the jobs for
          required: true
          schema:
            $ref: '#/definitions/PollData'
      responses:
        200:
          description: response
          schema:
            $ref: '#/definitions/Job1'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  HeartbeatResponse:
    properties:
      canceled:
        type: boolean
        
  Heartbeat:
    required:
      - progress
      - details
    properties:
      progress:
        type: integer
      details:
        type: string
  AckData:
    required:
      - jobID
      - workerID
    properties:
      jobID:
        type: string
      workerID:
        type: string
      
  PollData:
    required:
      - service
      - workerID
    properties:
      service:
        $ref: '#/definitions/Service'
      workerID:
        type: string
        example: "worker1"
  Service:
    required:
      - name
    properties:
      name:
        type: string
        example: "sample-service:1.0.0"
  Job1:
    required:
      - id
      - payload
    properties:
      id:
        type: string
      payload:
        type: object
      service:
        $ref: '#/definitions/Service'
  Job:
    required:
      - id
      - payload
    properties:
      id:
        type: string
        example : R8TEDg7tRoaUJ_ZfEI8ziDIyTGFVUlFQSXZSdmhlNmdLekhsV3IxZGUyV0hHeUFFVEtsR0ZDd2RnQ2UyTT0
      payload:
        type: object
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string